# Project: Organizing Netflix Movie Actor Rating Data

## Purpose

The purpose of this data analysis is to organize the average IMDB ratings of works featuring different actors across various film genres such as comedy, action, and science fiction, in order to identify high-rated actors within each genre.

The objective of this practical project is to practice organizing data to generate datasets suitable for subsequent analysis.

## Introduction

原始数据集记录了截止至2022年7月美国地区可观看的所有Netflix电视剧及电影数据。数据集包含两个数据表：`titles.csv`和`credits.csv`。

`titles.csv`包含电影及电视剧相关信息，包括影视作品ID、标题、类型、描述、流派、IMDB（一个国外的在线评分网站）评分，等等。`credits.csv`包含超过7万名出现在Netflix影视作品的导演及演员信息，包括名字、影视作品ID、人物名、演职员类型（导演/演员）等。

`titles.csv`每列的含义如下：
- id：影视作品ID。
- title：影视作品标题。
- show_type：作品类型，电视节目或电影。
- description：简短描述。
- release_year：发布年份。
- age_certification：适龄认证。
- runtime：每集电视剧或电影的长度。
- genres：流派类型列表。
- production_countries：出品国家列表。
- seasons：如果是电视剧，则是季数。
- imdb_id：IMDB的ID。
- imdb_score：IMDB的评分。
- imdb_votes：IMDB的投票数。
- tmdb_popularity：TMDB的流行度。
- tmdb_score：TMDB的评分。

`credits.csv`每列的含义如下：
- person_ID：演职员ID。
- id：参与的影视作品ID。
- name：姓名。
- character_name：角色姓名。
- role：演职员类型，演员或导演。

In [1]:
import pandas as pd

## Access

In [2]:
titles_data = pd.read_csv("titles.csv")
credits_data = pd.read_csv("credits.csv")

In [3]:
# Data Overview

titles_data.sample(10)

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
2021,tm298846,The Incredible Jessica James,MOVIE,"Burned by a bad breakup, a struggling New York...",2017,NaN,83,"['romance', 'comedy']",['US'],NaN,tt5990342,6.5,7667.0,9.638,6.200
1952,tm363103,Perfect Bid: The Contestant Who Knew Too Much,MOVIE,Maths teacher Ted Slauson became adept at reco...,2017,NaN,72,"['documentation', 'history']",['CA'],NaN,tt6854248,6.5,2665.0,4.334,6.500
444,tm110923,Divine Intervention,MOVIE,Santa Claus tries to outrun a gang of knife-wi...,2002,NaN,92,"['romance', 'comedy', 'drama', 'war']","['FR', 'MA', 'DE', 'PS']",NaN,tt0274428,6.6,3598.0,2.894,6.400
5031,tm977704,Robin Robin,MOVIE,A bird raised by mice begins to question where...,2021,G,30,"['animation', 'action', 'family', 'music', 'co...",['GB'],NaN,tt11332850,7.2,1533.0,46.420,7.100
4376,tm454464,Pegasus,MOVIE,"Zhang Chi, a hubris and dominating six-time ra...",2019,NaN,98,"['comedy', 'action', 'fantasy', 'sport']",['CN'],NaN,tt9597190,6.3,1813.0,5.369,6.300
5233,tm991351,Pelé,MOVIE,Against the backdrop of a turbulent era in Bra...,2021,PG-13,108,"['documentation', 'sport']",['GB'],NaN,tt13842562,7.0,4256.0,19.653,7.500
4393,ts234505,Fary: Hexagone,SHOW,French comedy phenom Fary puts a playful spin ...,2020,TV-MA,51,['comedy'],['FR'],1.0,tt11823028,6.2,129.0,1.410,7.000
2242,tm238377,The Legacy of a Whitetail Deer Hunter,MOVIE,A star of hunting videos strives to bond with ...,2018,NaN,83,"['comedy', 'drama']",['US'],NaN,tt4762824,5.5,3924.0,8.030,5.100
93,ts22176,Stargate SG-1,SHOW,The story of Stargate SG-1 begins about a year...,1997,TV-PG,44,"['scifi', 'drama', 'action']","['CA', 'US']",10.0,tt0118480,8.4,90196.0,88.851,8.300
245,ts20305,Naruto,SHOW,"In another world, ninja are the ultimate power...",2002,TV-PG,23,"['animation', 'action', 'scifi', 'comedy', 'fa...",['JP'],6.0,tt0409591,8.4,96729.0,218.843,8.363

There are structural issues on `'genres'` and `'country'`, however, we only need to focus on the `'genres'` bases on the purpose

In [4]:
credits_data.sample(10)

,person_id,id,name,character,role
76409,2234469,ts272422,Raegan Bernard,NaN,ACTOR
62469,311536,tm881973,Jamie Watson,NaN,ACTOR
46781,631836,tm426428,Josephine Langford,Tessa Young,ACTOR
73931,6456,tm993790,Tommy Flanagan,Petrov,ACTOR
2542,80917,tm116488,Paul Dillon,Prison Inmate who breaks TV,ACTOR
61255,1050869,tm456074,Dennis Jaffee,Chuck,ACTOR
20956,634480,tm120609,Adam Perry,Dancer,ACTOR
55337,114474,ts252166,Song Seon-mi,Kim Mi-Sook,ACTOR
68752,14002,ts269881,Hikaru Midorikawa,Thor (voice),ACTOR
64390,249850,tm1067148,Helen Sadler,Ms. Merino / Matron / Cart Driver (voice),ACTOR

此数据分析的目的是，整理不同流派影视作品，比如喜剧片、动作片、科幻片中，各演员出演作品的平均IMDB评分，从而挖掘出各个流派中的高评分作品演员。

Therefore, in `titles_data`, `"genres"` and `"imdb_score"` are important index; In `credits_data`, `"name"` and `"role"` are important index.

First, I should make sure the relevant data is clean and complete (delete irrelevant data), and then combine these two data into one table through `"id"`.

Afterwards, use `groupby` to sort out `"genres"` and `"name"`, and then use `mean()` to exhibit the rating of every actor.

## Clean

In [5]:
cleaned_titles = titles_data.copy()
cleaned_credits = credits_data.copy()

In [13]:
cleaned_titles.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15147 entries, 0 to 5849
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    15147 non-null  object
 1   title                 15146 non-null  object
 2   type                  15147 non-null  object
 3   description           15125 non-null  object
 4   release_year          15147 non-null  int64
 5   age_certification     9298 non-null   object
 6   runtime               15147 non-null  int64
 7   genres                15088 non-null  object
 8   production_countries  15147 non-null  object
 9   seasons               5923 non-null   float64
 10  imdb_id               14525 non-null  object
 11  imdb_score            14399 non-null  float64
 12  imdb_votes            14375 non-null  float64
 13  tmdb_popularity       14995 non-null  float64
 14  tmdb_score            14614 non-null  float64
dtypes: float64(5), int64(2), object(8)
memory usage: 1.8+ MB

In [14]:
cleaned_credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77801 entries, 0 to 77800
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   person_id  77801 non-null  int64
 1   id         77801 non-null  object
 2   name       77801 non-null  object
 3   character  68029 non-null  object
 4   role       77801 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.0+ MB

### Structure

In [7]:
cleaned_titles['genres'][1]

"['drama', 'crime']"

This means the type of `'genres'` is str instead of array

In [8]:
# Convert Type

cleaned_titles['genres'] = cleaned_titles['genres'].apply(lambda s: eval(s))
cleaned_titles['genres'][1]

['drama', 'crime']

In [12]:
cleaned_titles = cleaned_titles.explode('genres')
cleaned_titles.head(10)

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,documentation,['US'],1.0,NaN,NaN,NaN,0.600,NaN
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,drama,['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,crime,['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179
2,tm154986,Deliverance,MOVIE,Intent on seeing the Cahulawassee River before...,1972,R,109,drama,['US'],NaN,tt0068473,7.7,107673.0,10.010,7.300
2,tm154986,Deliverance,MOVIE,Intent on seeing the Cahulawassee River before...,1972,R,109,action,['US'],NaN,tt0068473,7.7,107673.0,10.010,7.300
2,tm154986,Deliverance,MOVIE,Intent on seeing the Cahulawassee River before...,1972,R,109,thriller,['US'],NaN,tt0068473,7.7,107673.0,10.010,7.300
2,tm154986,Deliverance,MOVIE,Intent on seeing the Cahulawassee River before...,1972,R,109,european,['US'],NaN,tt0068473,7.7,107673.0,10.010,7.300
3,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,fantasy,['GB'],NaN,tt0071853,8.2,534486.0,15.461,7.811
3,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,action,['GB'],NaN,tt0071853,8.2,534486.0,15.461,7.811
3,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,comedy,['GB'],NaN,tt0071853,8.2,534486.0,15.461,7.811

### Content

#### cleaned_titles

In [18]:
cleaned_titles[["genres", "imdb_score"]].isnull().sum()

genres         59
imdb_score    748
dtype: int64

In [20]:
cleaned_titles.dropna(subset=["genres", "imdb_score"], inplace=True) # apply to the DataFrame instead of Series (titles_data["imdb_score"].dropna())
cleaned_titles[["genres", "imdb_score"]].isnull().sum()

genres        0
imdb_score    0
dtype: int64

In [21]:
cleaned_titles.duplicated().sum()

np.int64(0)

In [22]:
cleaned_titles["genres"].value_counts()

genres
drama            2827
comedy           2218
thriller         1180
action           1109
romance           955
crime             909
documentation     859
family            652
animation         630
fantasy           619
scifi             560
european          428
horror            366
history           254
music             244
reality           219
sport             170
war               155
western            39
Name: count, dtype: int64

In [23]:
cleaned_titles["imdb_score"].value_counts()

imdb_score
6.3    520
6.5    520
7.1    510
6.7    509
6.6    505
      ...
2.2      3
1.6      3
1.7      3
2.4      2
1.9      1
Name: count, Length: 79, dtype: int64

In [26]:
cleaned_titles.query('genres == ""')

Empty DataFrame
Columns: [id, title, type, description, release_year, age_certification, runtime, genres, production_countries, seasons, imdb_id, imdb_score, imdb_votes, tmdb_popularity, tmdb_score]
Index: []

Make sure there is no missing/duplicated/wrong data in `cleaned_titles`

#### cleaned_credits

In [28]:
cleaned_credits[["name", "role"]].isnull().sum()

name    0
role    0
dtype: int64

In [29]:
cleaned_credits.duplicated().sum()

np.int64(0)

In [30]:
cleaned_credits["role"].value_counts()

role
ACTOR       73251
DIRECTOR     4550
Name: count, dtype: int64

Make sure there is no missing/duplicated/wrong data in `credits_data`, but I only need actors

In [34]:
cleaned_credits = cleaned_credits[cleaned_credits["role"] == "ACTOR"]
cleaned_credits["role"].value_counts()

role
ACTOR    73251
Name: count, dtype: int64

In [35]:
cleaned_credits["role"] = cleaned_credits["role"].astype("category")
cleaned_credits["role"]

0        ACTOR
1        ACTOR
2        ACTOR
3        ACTOR
4        ACTOR
         ...
77795    ACTOR
77796    ACTOR
77797    ACTOR
77798    ACTOR
77799    ACTOR
Name: role, Length: 73251, dtype: category
Categories (1, object): ['ACTOR']

## Organize

In [37]:
# 合并数据

credits_with_titles = pd.merge(cleaned_credits, cleaned_titles, on="id", how="inner")
credits_with_titles.sample(10)

,person_id,id,name,character,role,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
3517,216330,tm446654,Nutan,NaN,ACTOR,Mujrim,MOVIE,"The film follows the story of Shankar, who is ...",1989,NaN,162,crime,['IN'],NaN,tt0097926,5.4,197.0,1.418,6.000
96050,741114,tm414709,Ashley St. George,Christa,ACTOR,Siberia,MOVIE,"Lucas, a diamond trader who travels to Saint P...",2018,R,104,romance,"['CA', 'US', 'DE']",NaN,tt6494418,4.3,15369.0,22.000,4.800
117808,34549,tm324204,Roger L. Jackson,Nicolas (voice),ACTOR,Monster Island,MOVIE,Young Lucas finds out he's not really a human ...,2017,PG,80,family,"['IN', 'MX']",NaN,tt6269658,4.7,739.0,9.182,5.600
129194,39039,tm813695,Vince Pisani,Hotel Manager,ACTOR,After We Collided,MOVIE,Based on the 2014 romance novel of the same na...,2020,R,105,romance,['US'],NaN,tt10362466,5.0,30522.0,236.101,7.251
181510,897303,tm1020851,Thelma Plum,"Maeve, the Female Funnel Web Spider (voice)",ACTOR,Back to the Outback,MOVIE,Tired of being locked in a reptile house where...,2021,PG,95,family,"['AU', 'US']",NaN,tt13575806,6.5,7896.0,155.021,7.800
38345,44533,tm158304,Dan Flannery,Hextall's Father,ACTOR,Contagion,MOVIE,As an epidemic of a lethal airborne virus - th...,2011,PG-13,106,drama,"['AE', 'US']",NaN,tt1598778,6.8,301531.0,33.992,6.600
175323,1284185,tm1019177,Luna Mwezi,Girl 1,ACTOR,The Colony,MOVIE,In the not-too-distant future: after a global ...,2021,R,104,scifi,"['CH', 'DE']",NaN,tt6506264,5.3,8495.0,23.747,5.600
178509,122334,tm992844,Joe Hurst,John Jacobs,ACTOR,The Dig,MOVIE,"As WWII looms, a wealthy widow hires an amateu...",2021,PG-13,112,history,['GB'],NaN,tt3661210,7.1,73079.0,20.072,6.900
26647,391971,tm135451,Yasen Peyankov,Dr. Udvarhelyi,ACTOR,Gifted Hands: The Ben Carson Story,MOVIE,Gifted Hands: The Ben Carson Story is a movie ...,2009,NaN,86,drama,['US'],NaN,tt1295085,7.6,10881.0,43.409,7.800
45219,1168987,tm30278,Nadodigal Gopal,NaN,ACTOR,Vettai,MOVIE,Guru always helps his timid brother win accola...,2012,NaN,150,action,['IN'],NaN,tt1956697,6.0,2450.0,3.941,6.800

It would be better to use `'person_id'` as index instead of `'name'`

So we need to convert its type (int) into str

In [39]:
credits_with_titles['person_id'] = credits_with_titles['person_id'].astype(str)

In [40]:
# Apply groupby to get aimed data

groupby_genres_and_person_id = credits_with_titles.groupby(["genres", "person_id"], observed=True)
imdb_score_groupby_genres_and_person_id = groupby_genres_and_person_id["imdb_score"].mean()

In [41]:
imdb_score_groupby_genres_and_person_id

genres   person_id
action   1000         6.866667
         100007       7.000000
         100013       6.400000
         100019       6.500000
         100020       6.500000
                        ...
western  993735       6.500000
         998673       7.300000
         998674       7.300000
         998675       7.300000
         99940        4.000000
Name: imdb_score, Length: 168881, dtype: float64

In [42]:
organized_data = imdb_score_groupby_genres_and_person_id.reset_index()
organized_data

         genres person_id  imdb_score
0        action      1000    6.866667
1        action    100007    7.000000
2        action    100013    6.400000
3        action    100019    6.500000
4        action    100020    6.500000
...         ...       ...         ...
168876  western    993735    6.500000
168877  western    998673    7.300000
168878  western    998674    7.300000
168879  western    998675    7.300000
168880  western     99940    4.000000

[168881 rows x 3 columns]

## Analysis

**Next**:

1. Find the highest average rating of actors' works in each genre

2. identify the name of the actor with the highest rating

In [43]:
genres_max_score = organized_data.groupby("genres")["imdb_score"].max()

In [44]:
genres_max_score

genres
action           9.3
animation        9.3
comedy           9.2
crime            9.5
documentation    9.1
drama            9.5
european         8.9
family           9.3
fantasy          9.3
history          9.1
horror           9.0
music            8.8
reality          8.9
romance          9.2
scifi            9.3
sport            9.1
thriller         9.5
war              8.8
western          8.9
Name: imdb_score, dtype: float64

In [45]:
genres_max_score_with_person_id = pd.merge(organized_data, genres_max_score, on=["genres", "imdb_score"])

In [46]:
genres_max_score_with_person_id

      genres person_id  imdb_score
0     action     12790         9.3
1     action      1303         9.3
2     action     21033         9.3
3     action    336830         9.3
4     action     86591         9.3
..       ...       ...         ...
131      war    826547         8.8
132  western     22311         8.9
133  western     28166         8.9
134  western     28180         8.9
135  western     93017         8.9

[136 rows x 3 columns]

Then we need to find the connection bewteen `person_id` and `name`

In [49]:
actors_with_names = cleaned_credits[["person_id", "name"]].drop_duplicates()
actors_with_names['person_id'] = actors_with_names['person_id'].astype(str)
actors_with_names.sample(10)

      person_id                 name
71563   1795125      Pierce Turcotte
59898   1058544     Joshia Frederico
63947     89726       Tio Pakusadewo
74430    226999      Anil Nedumangad
2046      17378       Perico Sambeat
22449    325342       Jordana Keller
73837   2187592  Vasan Mahakiattikun
48518   1360750   Bianca de la Garza
42919    473694             Zhao Jun
32780    627624        Helen Daniels

In [50]:
genres_max_score_with_actors = pd.merge(genres_max_score_with_person_id, actors_with_names, on="person_id")

In [51]:
genres_max_score_with_actors

      genres person_id  imdb_score                name
0     action     12790         9.3         Olivia Hack
1     action      1303         9.3       Jessie Flower
2     action     21033         9.3          Zach Tyler
3     action    336830         9.3     André Sogliuzzo
4     action     86591         9.3       Cricket Leigh
..       ...       ...         ...                 ...
131      war    826547         8.8         Yuto Uemura
132  western     22311         8.9     Koichi Yamadera
133  western     28166         8.9  Megumi Hayashibara
134  western     28180         8.9      Unsho Ishizuka
135  western     93017         8.9            Aoi Tada

[136 rows x 4 columns]

In [52]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(genres_max_score_with_actors)

            genres person_id  imdb_score                  name
0           action     12790         9.3           Olivia Hack
1           action      1303         9.3         Jessie Flower
2           action     21033         9.3            Zach Tyler
3           action    336830         9.3       André Sogliuzzo
4           action     86591         9.3         Cricket Leigh
5        animation      1303         9.3         Jessie Flower
6        animation     21033         9.3            Zach Tyler
7        animation     28024         9.3           Dante Basco
8        animation    336830         9.3       André Sogliuzzo
9        animation     86591         9.3         Cricket Leigh
10          comedy    101292         9.2         Ryu Hye-young
11          comedy    103374         9.2            Lee Hye-ri
12          comedy   1296454         9.2          Lee Se-young
13          comedy    140194         9.2          Ryu Jun-yeol
14          comedy    140196         9.2          Ahn Jae-hong
15          comedy     38441         9.2           Park Bo-gum
16          comedy     44199         9.2         Kim Sung-kyun
17          comedy     71076         9.2             Ra Mi-ran
18          comedy    747462         9.2              Kim Seol
19           crime     20552         9.5          Betsy Brandt
20           crime     37752         9.5             Anna Gunn
21           crime     85485         9.5              RJ Mitte
22   documentation     22385         9.1        Michael Jordan
23   documentation     36303         9.1         Dennis Rodman
24   documentation    408553         9.1          Phil Jackson
25   documentation    439923         9.1            Steve Kerr
26   documentation    479703         9.1        Scottie Pippen
27           drama     20552         9.5          Betsy Brandt
28           drama     37752         9.5             Anna Gunn
29        european    107375         8.9         Sanjeev Kohli
30        european    107380         8.9              Mark Cox
31        european    170376         8.9         Greg Hemphill
32        european    317847         8.9        Gavin Mitchell
33        european    727786         8.9          Jane McCarry
34        european    727787         8.9            Paul Riley
35        european     86802         8.9          Ford Kiernan
36          family      1303         9.3         Jessie Flower
37          family     21033         9.3            Zach Tyler
38          family     28024         9.3           Dante Basco
39          family    336830         9.3       André Sogliuzzo
40          family     86591         9.3         Cricket Leigh
41         fantasy      1303         9.3         Jessie Flower
42         fantasy     21033         9.3            Zach Tyler
43         fantasy     28024         9.3           Dante Basco
44         fantasy    336830         9.3       André Sogliuzzo
45         fantasy     86591         9.3         Cricket Leigh
46         history     22385         9.1        Michael Jordan
47         history     36303         9.1         Dennis Rodman
48         history    408553         9.1          Phil Jackson
49         history    439923         9.1            Steve Kerr
50         history    479703         9.1        Scottie Pippen
51          horror       140         9.0          Ayane Sakura
52          horror     39331         9.0          Marina Inoue
53          horror    453970         9.0        Kisho Taniyama
54          horror     86694         9.0          Yui Ishikawa
55           music   1033815         8.8             Adam Cole
56           music   1284975         8.8         Lisa Reynolds
57           music    129032         8.8        Virgile Bramly
58           music     14204         8.8        Nicole Pulliam
59           music   1625708         8.8      Mark Fleischmann
60           music      1640         8.8             Tom Hardy
61           music      1641         8.8     Leonardo DiCaprio
62           music      1652         8.8            Lukas Haas
63           music     16641         8.8          Taylor Geare
64           music      1710         8.8             Russ Fega
65           music   1789502         8.8         Jill Maddrell
66           music      2150         8.8         Talulah Riley
67           music   2269290         8.8     Daniel Girondeaud
68           music    231310         8.8      Natasha Beaumont
69           music      2740         8.8        Michael Gaston
70           music     27692         8.8          Alex Lombard
71           music      2806         8.8           Elliot Page
72           music    294917         8.8          Marc Raducci
73           music      3010         8.8  Joseph Gordon-Levitt
74           music      3011         8.8          Ken Watanabe
75           music      3012         8.8        Cillian Murphy
76           music      3013         8.8            Dileep Rao
77           music      3014         8.8      Marion Cotillard
78           music      3015         8.8          Tom Berenger
79           music      3016         8.8    Pete Postlethwaite
80           music    301776         8.8        Shannon Welles
81           music    351504         8.8       Johnathan Geare
82           music    351505         8.8          Ryan Hayward
83           music    351506         8.8      Coralie Dedykere
84           music    351507         8.8         Nicolas Clerc
85           music    351508         8.8    Jean-Michel Dagory
86           music    392464         8.8           Felix Scott
87           music     46263         8.8          Yuji Okumoto
88           music      4726         8.8          Tim Kelleher
89           music     52379         8.8          Claire Geare
90           music      5811         8.8        Andrew Pleavin
91           music     77040         8.8         Miranda Nolan
92           music     77136         8.8       Tohoru Masamune
93           music     77469         8.8          Peter Basham
94           music     82056         8.8         Carl Gilliard
95           music     84050         8.8          Earl Cameron
96           music     85756         8.8           Jack Murray
97           music     91220         8.8         Silvie Laguna
98           music    984016         8.8            Tai-Li Lee
99           music    984017         8.8          Magnus Nolan
100          music    984023         8.8       Helena Cullinan
101        reality   1099510         8.9        Niklas Ekstedt
102        reality       614         8.9     Heston Blumenthal
103        reality    843741         8.9           Jayde Adams
104        reality    958249         8.9            Carla Hall
105        romance    101292         9.2         Ryu Hye-young
106        romance    103374         9.2            Lee Hye-ri
107        romance    103760         9.2          Sung Dong-il
108        romance   1296454         9.2          Lee Se-young
109        romance    140194         9.2          Ryu Jun-yeol
110        romance    140195         9.2          Lee Dong-hwi
111        romance    140196         9.2          Ahn Jae-hong
112        romance     44199         9.2         Kim Sung-kyun
113        romance     71076         9.2             Ra Mi-ran
114        romance    747462         9.2              Kim Seol
115          scifi     12790         9.3           Olivia Hack
116          scifi      1303         9.3         Jessie Flower
117          scifi     21033         9.3            Zach Tyler
118          scifi     28024         9.3           Dante Basco
119          scifi    336830         9.3       André Sogliuzzo
120          scifi     86591         9.3         Cricket Leigh
121          sport     22385         9.1        Michael Jordan
122          sport     36303         9.1         Dennis Rodman
123          sport    408553         9.1          Phil Jackson
124          sport    439923         9.1            Steve Kerr
125          sport    479703         9.1        Scottie Pippen
126       thriller     13233         9.5          Bob Odenkirk
127       thriller     20552         9.5          Betsy Brandt
128       thriller     37752         9.5             Anna Gunn
129            war    140181         8.8          Naoya Uchida
130            war     47019         8.8            Kensho Ono
131            war    826547         8.8           Yuto Uemura
132        western     22311         8.9       Koichi Yamadera
133        western     28166         8.9    Megumi Hayashibara
134        western     28180         8.9        Unsho Ishizuka
135        western     93017         8.9              Aoi Tada